spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          - id: leave-service
            uri: lb://leave-service
            predicates:
              - Path=/api/leaves/**
          - id: leave-service-holidays
            uri: lb://leave-service
            predicates:
              - Path=/api/holidays/**
          - id: leave-service-chatbot
            uri: lb://leave-service
            predicates:
              - Path=/api/chatbot/**
    loadbalancer:
      cache:
        ttl: 5s

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
