spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
    loadbalancer:
      cache:
        ttl: 5s

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
    eureka-server-read-timeout-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
